version: '3.7'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /opt/docker-compose/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
#      - 'usb-Silicon_Labs_Zooz_ZST10_700_Z-Wave_Stick_0faa85bc3b1ca74945cde2234df471a7a-if00-port0:/dev/ttyZWave'
      - '/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyZigbee'
    restart: unless-stopped
    privileged: true
    network_mode: host

  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:latest
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      # Uncomment if you want logs time and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      #- TZ=America/New_York
      - TZ=America/Denver
    networks:
      - zwave
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - '/dev/serial/by-id/usb-Silicon_Labs_Zooz_ZST10_700_Z-Wave_Stick_0faa85bc3b1ca74945cde2234df471a7a-if00-port0:/dev/zwave'
    volumes:
      - zwave-config:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server
networks:
  zwave:
volumes:
  zwave-config:
    name: zwave-config

